services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: getoutside
      POSTGRES_PASSWORD: getoutside
      POSTGRES_DB: getoutside
    volumes:
      - getoutside_pg:/var/lib/postgresql/data

volumes:
  getoutside_pg:
